name: Python tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    name: test
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        # Exclude the `PYTHON_VERSION` in `Makefile`. This is tested in codecov
        python-version: ["3.9", "3.10"]

    steps:
    - name: Checkout reptar
      uses: actions/checkout@v4
    
    - name: Checkout reptar-data
      uses: actions/checkout@v4
      with:
        repository: 'oasci/reptar-data'
        lfs: true
        path: examples/reptar-data
    
    - name: Install miniconda
      uses: conda-incubator/setup-miniconda@v2
      with:
        miniconda-version: "latest"
        auto-update-conda: true
        python-version: ${{ matrix.python-version }}
      
    - name: Initialize conda environment
      run: make conda-setup
    
    - name: Install conda packages
      run: make from-conda-lock
    
    - name: Poetry install
      run: make install
    
    - name: Run tests and coverage
      run: make test
